apiVersion: v1
kind: Service
metadata:
  name: cobalt-instance-svc
  namespace: homelab
  labels:
    name: cobalt-instance-svc
  annotations:
    name: cobalt-instance-svc
spec:
  # type: NodePort 
  type: ClusterIP 
  ports:
    - port: 9000
      name: http
      targetPort: http
      protocol: TCP
      # nodePort: 30001
  selector:
    name: cobalt-instance
