apiVersion: apps/v1
kind: Deployment
metadata:
  name: metube
  namespace: homelab
  labels:
    name: metube
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: metube
  template:
    metadata:
      labels:
        name: metube
        egress: lan
        ingress: lan
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: metube # https://github.com/alexta69/metube
          image: "ghcr.io/alexta69/metube" # 
          envFrom:
            - configMapRef:
                name: metube-configmap
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          volumeMounts:
            - mountPath: /downloads
              name: downloads 
          securityContext:
            allowPrivilegeEscalation: false
            # runAsUser: 1000
            # runAsGroup: 1000
      volumes:
        - name: downloads 
          persistentVolumeClaim:
            claimName: metube-local-downloads-pvc
